config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :people
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def new
    @person=Person.new
  end

  def edit
    @person=Person.find(params[:id])
  end

  def create
    @person=Person.new(person_params)

    @person.save
    redirect_to @person
  end

  def index
    @people=Person.all
  end
   
  def show
    @person=Person.find(params[:id])
  end

  def update
    @person=Person.find(params[:id])

    @person.update(person_params)
    redirect_to @person
  end

  def destroy
    @person=Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private
    def person_params
      params.require(:person).permit(:name,:age)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with model: @person, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>List of People</h1>
<%= link_to 'New Person', new_person_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th colspan="3"></th>
  </tr>

  <% @people.each do |person| %>
    <tr>
      <td><%= person.name %></td>
      <td><%= person.age %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %>
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<h1>Hey, its my first RESTful service!!!</h1>
<%= link_to 'My Friends', controller: 'people' %>